### PR TITLE
Gitlab

### LINKED ISSUE #11: Move CI to gitlab
Remove Jenkins CI in favor of gitlab CI

- create a .gitlab-ci.yml
- create gitlab account
- set up CI pipeline

Helpful samples:
https://github.com/samsung-cnct/cyklops-events/pull/7/files
https://github.com/joejulian/chart-ingress-nginx/pull/1/files

### PR DESCRIPTION
**Pull request by guineveresaenger**
Fixes #11

### CODE REVIEW

**Comment by guineveresaenger** [comment]
This PR really just adds the gitlab-ci.yml. Actual execution of CI in gitlab is pending integration of github into gitlab, which is being done elsewhere currently.

**Comment by guineveresaenger** [comment]
Tying into the discussion on https://github.com/samsung-cnct/ci-evaluation/issues/40,
the `publish` stage of this CI will push to `:latest` on Quay, while a version-tagged commit (or just the added version tag, if I understand git tags correctly) will push to Quay with that particular tag.

**Comment by leahnp** [comment]
@guineveresaenger do we have documentation for this process anywhere? I'd like to get a better sense of where these env vars are coming from.

**Comment by guineveresaenger** [comment]
@leahnp yes! There are a couple open PR's on solas and solas-container. Let me know if those directions make sense to you.
I will say that some of the variables are provided by GitLab itself, and if that should be made more clear, let me know over there.
https://github.com/samsung-cnct/solas-container/issues/17

**Comment by leahnp** [comment]
@guineveresaenger - I think we should merge this, just one more request from me. Can you write up some review instructions that outline `how to check these jobs in GitLab?` I just setup my GitLab account and would like to learn how to check PR's and master branch CI.

**Comment by guineveresaenger** [comment]
@leahnp I am still tinkering with adding a cleanup stage, as per @venezia 's suggestion on https://github.com/samsung-cnct/solas-container/pull/18 so will keep you posted. Thank you for reviewing!

**Pull request merged**
